on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    name: writes a file from docker action
    steps:
      - name: Docker step
        uses: travisdowns/gha-docker-issue@master
      - name: 
        run: |
          echo "id outside the container: $(id)"
          touch hello-outside
          ls -l
          
